# Generated by Django 3.1.5 on 2021-01-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digimon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digimon',
            old_name='skill',
            new_name='Skill',
        ),
    ]
